### ISSUE TITLE
Binary XML file line #0: Error inflating class com.lucasurbas.listitemview.ListItemView

### ISSUE THREAD

**Issue by iman2420** [lurbas/ListItemView#12]
This is my layout item :

     `<?xml version="1.0" encoding="utf-8"?>
      <com.lucasurbas.listitemview.ListItemView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/car_list_item_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:liv_displayMode="icon"
        app:liv_icon="@drawable/ic_launcher_foreground"
        app:liv_menu="@menu/car_list_single_action_menu"
        app:liv_subtitle="@string/car_list_subtitle"
        app:liv_title="@string/car_list_title"/>`

but i got **InflateException**:

     `android.view.InflateException: Binary XML file line #0: Error inflating class com.lucasurbas.listitemview.ListItemView
`

**Comment by passsy** [comment]
Is there further information in the stacktrace?

**Comment by ejbp** [comment]
I'm also having this problem:


compileSdkVersion 26
minSdkVersion 21
targetSdkVersion 26

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/white"
    tools:context="pt.eduardopinheiro.clocktouch.SettingActivity">


    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="160dp">

        <com.lucasurbas.listitemview.ListItemView
            android:id="@+id/list_item_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/white"
            app:liv_title="@string/admin_title"
            app:liv_subtitle="@string/admin_subtitle"
            app:liv_icon="@drawable/ic_settings_black_24dp"
            app:liv_menu="@menu/menu_admin"
            app:liv_multiline="false"
            app:liv_displayMode="icon"/>

    </FrameLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="#bbbbbb" />

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:animateLayoutChanges="true"
            android:orientation="vertical">

            <com.lucasurbas.listitemview.ListItemView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:liv_subtitle="@string/manage_school_classes" />

            <com.lucasurbas.listitemview.ListItemView
                android:id="@+id/attr_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:liv_title="@string/manage_students" />

        </LinearLayout>




    </ScrollView>


</RelativeLayout>

```



```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:app="http://schemas.android.com/apk/res-auto"
      xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:id="@+id/action_add_school_class"
        android:icon="@drawable/ic_add_circle_outline_black_24dp"
        android:title="@string/manage_school_classes"
        app:showAsAction="always" />

    <item
        android:id="@+id/action_info"
        android:icon="@drawable/ic_child_care_black_24dp"
        android:title="@string/manage_students"
        app:showAsAction="always" />

</menu>
```


```
FATAL EXCEPTION: main
Process: com.xxxx, PID: 20397
java.lang.RuntimeException: Unable to start activity ComponentInfo{pt.eduardopinheiro.clocktouch/pt.eduardopinheiro.clocktouch.SettingActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.lucasurbas.listitemview.ListItemView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2452)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
    at android.app.ActivityThread.access$900(ActivityThread.java:158)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5515)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
 Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.lucasurbas.listitemview.ListItemView
    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
    at android.app.Activity.setContentView(Activity.java:2275)
    at pt.eduardopinheiro.clocktouch.SettingActivity.onCreate(SettingActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:6459)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
    at android.app.ActivityThread.access$900(ActivityThread.java:158) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5515) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
 Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.lucasurbas.listitemview.ListItemView
    at android.view.LayoutInflater.createView(LayoutInflater.java:645)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412) 
    at android.app.Activity.setContentView(Activity.java:2275) 
    at pt.eduardopinheiro.clocktouch.SettingActivity.onCreate(SettingActivity.java:18) 
    at android.app.Activity.performCreate(Activity.java:6459) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
    at android.app.ActivityThread.access$900(ActivityThread.java:158) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5515) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.view.LayoutInflater.createView(LayoutInflater.java:619)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412) 
    at android.app.Activity.setContentView(Activity.java:2275) 
    at pt.eduardopinheiro.clocktouch.SettingActivity.onCreate(SettingActivity.java:18) 
    at android.app.Activity.performCreate(Activity.java:6459) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
    at android.app.ActivityThread.access$900(ActivityThread.java:158) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5515) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
 Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at com.lucasurbas.listitemview.util.view.MenuView.createActionView(MenuView.java:235)
    at com.lucasurbas.listitemview.util.view.MenuView.reset(MenuView.java:156)
    at com.lucasurbas.listitemview.util.view.MenuView.reset(MenuView.java:230)
    at com.lucasurbas.listitemview.ListItemView.inflateMenu(ListItemView.java:496)
    at com.lucasurbas.listitemview.ListItemView.setupView(ListItemView.java:257)
    at com.lucasurbas.listitemview.ListItemView.init(ListItemView.java:199)
    at com.lucasurbas.listitemview.ListItemView.<init>(ListItemView.java:171)
    at java.lang.reflect.Constructor.newInstance(Native Method) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412) 
    at android.app.Activity.setContentView(Activity.java:2275) 
    at pt.eduardopinheiro.clocktouch.SettingActivity.onCreate(SettingActivity.java:18) 
    at android.app.Activity.performCreate(Activity.java:6459) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512) 
    at android.app.ActivityThread.access$900(ActivityThread.java:158) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5515) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654) 
 Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>
    at android.view.LayoutInflater.createView(LayoutInflater.java:645)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.infl
```

**Comment by sankhakarfa** [comment]
I had the same problem but using an XML instead of a png worked for me.

**Comment by lurbas** [comment]
Thank you for raising the issue. I took a look at it today. Unfortunately, couldn't reproduce it. Tried on different sdk versions (19, 21, 26) without any luck. Also tried with a mix of vector and png drawables. If you could send me a link to small project on github which presents described crash, I would be able to verify it and make a fix. Thanks in advance.

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @ghosharindam, @mrinalwadhwa, @Kirhchoff, @jimicy, @ay18, @mihail911, @geekiyer, @K-Ho, @fondroid, @thirdy, @dcbuild3r, @jobez, @firattale, @robinchu, @dec0dOS, @zambon, @gbrassey, @calldata, @pawanjay176, @yomikoye, @stevedoor, @flashmob, @antonper, @HariharasudhanAS, @gaahrdner, @wenweih, @outmost, @rrbrambley, @raviqqe, @johan-105, @CJamesKeller, @lacrosse, @chris-shelton, @knarfben, @BrRenat, @pedmiston, @spacecomputer, @NickBrooks, @suyanlong, @MansurovB-source, @santiagopoli, @wnklb, @blockchainian, @nRewik, @atmoz, @dipaksaraf, @cooldeepVP, @colinbowen, @robotzero, @tasti

**Comment by H4wk-eye** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Siunami, @Ag-E, @SJCaldwell, @spovich, @tlatkdgus1, @gl2748, @jumalo, @huangliang2211, @Showyilu, @danqing, @vikaskyadav, @viatcheslavmogilevsky, @youngguncho, @jimicy, @atimur, @Celebes, @Claudiabttrcp, @ricburton, @avinash-oza, @zshvvhm
